import Head from "next/head";
import PersonalInfo from "../components/personal-info";

export default function AboutMe() {
  return (
    <div className="flex flex-col items-center justify-center w-50 p-10 mt-20">
      <Head>
        <title>My Portfolio - About me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl my-3 font-bold text-blush">About me</h1>

      <PersonalInfo />
    </div>
  );
}
