import Head from "next/head";
import V2ContactForm from "../components/v2.contactform";

export default function Contact() {
  return (
    <div className="flex flex-col items-center text-center w-50 p-10 mt-20">
      <Head>
        <title>My Portfolio - Contact me</title>
        <meta
          name="description"
          content="This is my portfolio. Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl my-3 font-bold text-blush">Contact me!</h1>

      <div className="flex flex-col sm:flex-row sm:gap-20 my-4 p-2">
        <div className="flex flex-col gap-5 sm:max-w-[50%]">
          <p className="text-center">
            I would love to get in touch with you. Send me an e-mail, contact me
            on LinkedIn,
          </p>
          <button className="text-white bg-purple p-2 mt-4 rounded hover:bg-white hover:text-purple hover:translate-x-1 transition-color duration-200 delay-180 ">
            <a href="https://www.linkedin.com/in/petra-johansson-4a2461229/">
              {" "}
              Go to my LinkedIn and get in touch
            </a>
          </button>
          <button
            className="text-white bg-purple p-2 mt-4 rounded hover:bg-white hover:text-purple hover:translate-x-1 transition-color duration-200 delay-180 "
            onClick={() =>
              (window.location.href = "mailto: johansson.m.petra@gmail.com")
            }
          >
            {" "}
            Send me an e-mail
          </button>
        </div>
        <div className="mt-10 sm:mt-0 min-w-[50%]">
          <V2ContactForm />
        </div>
      </div>
    </div>
  );
}
