import Head from "next/head";
import ContactForm from "../components/contactform";

export default function Contact() {
  return (
    <div className="flex flex-col items-center text-center w-50 p-10 mt-20">
      <Head>
        <title>My Portfolio - Contact me</title>
        <meta
          name="description"
          content="This is my portfolio. Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl my-3 font-bold text-blush">Contact me!</h1>

      <div className="flex flex-col sm:flex-row sm:gap-20 my-4 p-2">
        <div className="flex flex-col gap-5">
          <p className="text-center">
            I would love to get in touch with you. Send me an e-mail, contact me
            on LinkedIn,
          </p>
          <button className="text-white bg-purple hover:bg-white hover:text-purple p-2 mt-4 rounded">
            <a href="https://github.com/Petra-Johansson">
              {" "}
              Go to my LinkedIn and get in touch
            </a>
          </button>
          <button
            className="text-white bg-purple hover:bg-white hover:text-purple p-2 mt-4 rounded"
            onClick={() =>
              (window.location.href = "mailto: johansson.m.petra@gmail.com")
            }
          >
            {" "}
            Send me an e-mail
          </button>
        </div>
        <div className="mt-10 sm:mt-0">
          <p className="mb-2">Or simply fill out this contact form!</p>
          <ContactForm />
        </div>
      </div>
    </div>
  );
}
