import CvView from "../components/cvView";
import Head from "next/head";

export default function CV() {
    return (
        <div className="flex flex-col items-center justify-center w-50 p-10 mt-20">
            <Head>
        <title>My Portfolio - CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h2 className="text-4xl my-3 font-bold text-blush">This my CV</h2>

        <CvView/>
        </div>
    )
}