import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";

export default function Home() {
  return (
    <div class="bg-red-500">
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
        <div className="text-green">
          <Hero />
        </div>
     
    </div>
  );
}
