import Head from "next/head";

export default function Projects() {
    return(
        <div className="flex flex-col items-center justify-center w-50 p-10 mt-20">
            <Head>
        <title>My Portfolio - My Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl my-3 font-bold text-blush">My Projects</h1>

      <p>In here I will display completed projects that might be of interest. </p>
        </div>
    )
}